### ISSUE TITLE
Problem with some functionality of the TLM mod.

### ISSUE THREAD

**Issue by Radman-20** [klyte45/TransportLinesManager#222] opened 2022-02-21 10:16 UTC
1. Nearest tram routes are not displayed on buildings. Trolleybus and bus are displayed.
![03](https://user-images.githubusercontent.com/98400480/154934111-49147dc6-2a82-4c96-b420-11e5316184a2.jpg)
![01](https://user-images.githubusercontent.com/98400480/154934118-2d9c8d44-cf00-47e8-9550-9a79e5099ca9.jpg)
![02](https://user-images.githubusercontent.com/98400480/154934122-34415bdd-c1e4-4486-b5b2-b80bfa9de75c.jpg)

2. Transport goes to the depot with passengers. It started after installing the official game patch 1.14.0-f9 
![12](https://user-images.githubusercontent.com/98400480/154934221-6af496ec-8463-442b-a912-4fea77bf1c0b.jpg)
![10](https://user-images.githubusercontent.com/98400480/154934230-cbd2135c-b71c-4425-83ad-f0e87aa8024c.jpg)
![11](https://user-images.githubusercontent.com/98400480/154934233-7d91d616-210f-46b0-9c2d-9ee7fbc4f7de.jpg)
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/8108298/output_log.txt)

**Comment by klyte45** [comment] 2022-03-25 22:00
Duplicate of #215

**Closed by klyte45** 2022-03-25 22:00 UTC
Labels: new bug
