### ISSUE TITLE
Found Possible Cause and Fix for Trains Stuck At Boarding

### ISSUE THREAD

**Issue by ILikeFreightTrains** [klyte45/TransportLinesManager#155] opened 2021-10-30 14:37 UTC
So I was looking at a train in a station, and a passenger started walking in the opposite direction of the train, going in the opposite direction of their destination too, and they would ignore roads, terrain height, etc. I followed the citizen and noticed that the train was still at the station, with several other trains on the same line backed up. I used TMPE to remove the citizen, and the instant I did that the train started moving. I've noticed this happen other times, and now 2/5 of the time a train is stuck at boarding I find and delete one of those floating citizens and the train starts moving normally.

Edit: I forgot to mention that sometimes the passenger gets shot out of the station but starts to walk back towards the train. Once the get back to the train, it immediately starts moving.
Maybe this can be used to help fix the problem more?

**Comment by Vectorial1024** [comment] 2021-11-10 11:45
And yes this I also found for buses too, my guess is that this happens for basically every kind of transport. I have a main metro line in my city and sometimes this happens and then the traffic along the highway is suddenly very congested because CIMs decided to ditch the metro and just drive to their destination due to this bug.

It was much earlier when users are saying that the buses under Express Bus Services suddenly refused to depart, and then I used ModTools to poke around and also found out this problem.

CIMs would randomly decide to not despawn when they are about to enter a vehicle + start to straight-line walk to the next stop and back, causing the vehicle to become confused because someone still hasnt boarded yet and cannot depart.

I call this the "Citizen Runaway Problem" (CRP).

I have already provided a fix to the bus+trolleybus CRP case in EBS, but decided I was lazy enough to not also do the other types of transport. Depending on the situation maybe TLM could adapt my logic and apply the fix for all kinds of transport.

**Comment by klyte45** [comment] 2021-12-11 23:59
I confirm that I had this issue here some times while in tests for 14.1, but I believe it was fixed with the forced despawn when the line is closed logic. 
However, I can't ensure it because I have no idea about how to reproduce this issue.

**Comment by Vectorial1024** [comment] 2021-12-13 10:16
When I was testing my EBS I noticed this bug even when the bus lines in question are "full-day" routes, meaning it does not go to 0% budget in any moment in the 24 hr schedule.

I understand this as some sort of "mysterious behavior": we need not really explain how it happened, just take it as granted that "it just happens, and it is not OK". Dont wanna spend too much time trying to debug a bug that is best solved by Colossal Order. Just make a quick hack so that it woks again.

I then noticed the above mentioned behavior where in a small chance, some CIMs would fail to despawn when entering vehicle and everything just stands still. The corresponding hack is then to force the CIMs to despawn; hopefully when they exit the vehicle they exit right at the stop and everything is OK again.

**Comment by klyte45** [comment] 2021-12-14 02:40
Well, since it's very rare, I will close this issue for now. If we find some relevant clue in this matter I will reopen it.

**Closed by klyte45** 2021-12-14 02:40 UTC
Labels: question

**Comment by Vectorial1024** [comment] 2022-03-06 19:16
An update:

I have released a new mod Public Transport Unstucker https://github.com/Vectorial1024/PublicTransportUnstucker that solves the Citizen Runaway Problem for all types of public transport, including buses, metros, trains, etc.

So when you decide to use that mod, you should find that public transport especially trains become more efficient.
