### ISSUE TITLE
Misaligned budget table cells

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#65] opened 2021-04-24 08:38 UTC
For example, like this:

![Screenshot (19)](https://user-images.githubusercontent.com/17726797/115952889-4c6f6180-a51b-11eb-9b4c-2904ee709cf8.png)

Not particularly game-breaking but it is often inconvenient trying to read the profits and losses.

Similar misalignment also occurs in the other tabs e.g. wealth, age-group, etc.

**Comment by klyte45** [comment] 2021-04-24 09:58
Duplicate of #45 
Are your resolution 1440p?

**Comment by Vectorial1024** [comment] 2021-04-24 13:16
I read through the referenced thread, and yes my screen is 1440p; but I am not running the game at 1440p, so I perhaps could try with a different resolution

**Comment by klyte45** [comment] 2021-04-24 23:21
Well, I released a new version that may solve this problem, please take a look at alpha branch.
Closing this issue, watch #45 for news.

**Closed by klyte45** 2021-04-24 23:21 UTC
Labels: duplicate
