### ISSUE TITLE
Flickering menu in content manager

### ISSUE THREAD

**Issue by Jorgen-P** [klyte45/TransportLinesManager#38] opened 2020-01-17 20:58 UTC
When I enable this mod (version from Steam workshop) the game loads for a second (does not happen for other mods) and reverts to the map view of content manager. Every time after this I click to enable another mod the main menu flickers into view. The flickering starts/stops when I enable/disable TLM but the view change and loading happens only the first time.

I have tried disabling all other mods and restarting the game and verifying the game through Steam (no problems found) and the issue persists.

**Comment by klyte45** [comment] 2020-01-17 21:21
I need:
- Your full mod list (even disabled mods count)
- Your OS
- Some screenshots, if possible
- Your game log, after running a session that it occurred

Thanks!

**Comment by Jorgen-P** [comment] 2020-01-19 08:17
Thank you for the quick reply.

OS: Windows 10 Pro version 1909

Link to video (should play in browser):
https://www.dropbox.com/s/36ya188l1cwbznq/2020.01.19-08.44.mp4?dl=0

Is this the correct log file?: C:\Program Files (x86)\Steam\steamapps\common\Cities_Skylines\Cities_Data\output_log.txt
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/4082406/output_log.txt)

Mods:
* Transport Lines Manager 13
* Move it
* Precision engineering
* Crossings
* Clouds & Fog Toggler
* Real Natural LUT
* Softer Shadows
* Standard Parking garage (asset, not mod)
* Empty it!
* Bullzode it!
* Purchase it!
* Achieve it!
* Roundabout builder
* BigCity (25 tiles mod)
* Fine Road Tool 2.0.3
* Fine Road Anarchy
* Traffic Manager: President Edition [STABLE]
* Daylight Classic
* Real Time

**Comment by klyte45** [comment] 2020-01-19 14:26
Well, this is a harmless effect caused by the tabs on options menu of TLM. Once it doesn't cause any problem (besides the need of select the mod tab again) it won't be fixed. The fix would be remove the tabs from options menu, generating a log scroll screen (ugly and confused, like it was before version 8)
So, closing...

**Closed by klyte45** 2020-01-19 14:26 UTC
