### ISSUE TITLE
[BUG]TypeLoadException: Could not load type 'UnifiedUI.Helpers.UUIHotKeys' from assembly 'TransportLinesManager'.

### ISSUE THREAD

**Issue by artur6768** [klyte45/TransportLinesManager#227] opened 2022-03-02 22:07 UTC
**Describe the bug**
Mod works partially, it's possible to create new lines, and the previous lines are working fine, but it's impossible to open the lines overview tab.

**To Reproduce**
Just startup a save, then the bug will appear 

**Game Logs**
TypeLoadException: Could not load type 'UnifiedUI.Helpers.UUIHotKeys' from assembly 'TransportLinesManager'.
at Klyte.Commons.Interfaces.BasicIUserMod`3.OnLevelLoadedInherit (ICities.LoadMode) <0x001c5>
at Klyte.Commons.Interfaces.BasicIUserModSimplified`2.OnLevelLoaded (ICities.LoadMode) <0x00029>
at (wrapper dynamic-method) LoadingWrapper.LoadingWrapper.OnLevelLoaded_Patch6 (LoadingWrapper,SimulationManager/UpdateMode) <0x000b9>

Rethrow as ModException: The Mod F:\SteamLibrary\steamapps\workshop\content\255710\1312767991 [0Harmony.dll, TransportLinesManager.dll] has caused an error

UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
LoadingWrapper:LoadingWrapper.OnLevelLoaded_Patch6(LoadingWrapper, UpdateMode)
<LoadLevelComplete>c__Iterator9:MoveNext()
LoadingManager:FpsBoosterUpdate()
BehaviourUpdater.Updater:Update()

**Screenshots**
![imagen](https://user-images.githubusercontent.com/96083801/156456157-8025c20c-efa6-4bdc-bdbc-3ce020c6a635.png)

**Comment by Vectorial1024** [comment] 2022-03-10 02:59
Could be related to #220

**Comment by klyte45** [comment] 2022-03-25 22:22
Duplicate of #220

**Closed by klyte45** 2022-03-25 22:22 UTC
Labels: new bug
