### ISSUE TITLE
Consistent Exception Errors and No Spawning of Metro Vehicles With Release 14.2 r8  With Metro Overhaul Mod

### ISSUE THREAD

**Issue by Boliqua2** [klyte45/TransportLinesManager#174] opened 2021-12-18 02:27 UTC
Good evening Klyte45,
I greatly appreciate your work  and an avid user of TLM for years now.

This 14.2 r8 release I am having the following issue
I am having issues with using Metro Overhaul Mod With TLM which I had no issue with before the 14.2 release

I am constantly getting exception errors ever few seconds and none of my metro vehicles are spawning. 
It unfortunately makes the game unplayable for me currently and I want to continue to use TLM
I attached some exception errors I get regularly. Also attaching Also I attached some screenshots

System.NullReferenceException: Object reference not set to an instance of an object
at Klyte.TransportLinesManager.Utils.TLMDepotUtils.GetAllDepotsFromCity (Klyte.TransportLinesManager.Extensions.TransportSystemDefinition) <0x001a8>
at Klyte.TransportLinesManager.Extensions.ExtensionStaticExtensionMethods.GetAllowedDepots<Klyte.TransportLinesManager.Interfaces.IBasicExtension> (Klyte.TransportLinesManager.Interfaces.IBasicExtension,Klyte.TransportLinesManager.Extensions.TransportSystemDefinition,uint16) <0x00072>
at Klyte.TransportLinesManager.Overrides.TLMDepotAIOverrides.SetRandomBuilding (Klyte.TransportLinesManager.Extensions.TransportSystemDefinition,uint16,uint16+) <0x0005c>
at Klyte.TransportLinesManager.Overrides.TLMDepotAIOverrides.StartTransfer (DepotAI,uint16,TransferManager/TransferReason,TransferManager/TransferOffer) <0x002ed>
at (wrapper dynamic-method) DepotAI.DepotAI.StartTransfer_Patch1 (DepotAI,uint16,Building+,TransferManager/TransferReason,TransferManager/TransferOffer) <0x0009a>
at TransferManager.StartTransfer (TransferManager/TransferReason,TransferManager/TransferOffer,TransferManager/TransferOffer,int) <0x00643>
at (wrapper dynamic-method) TransferManager.TransferManager.MatchOffers_Patch1 (TransferManager,TransferManager/TransferReason) <0x0077c>
at TransferManager.SimulationStepImpl (int) <0x00070>
![20211216070220_1](https://user-images.githubusercontent.com/96257445/146625798-09b333ec-407f-428d-b186-23a7b6997f05.jpg)
![20211216223838_1](https://user-images.githubusercontent.com/96257445/146625800-76f54e43-b8a7-45be-852f-77390ab42cbe.jpg)
![20211216224320_1](https://user-images.githubusercontent.com/96257445/146625801-7ed0dbc5-774c-4a24-a3b1-9acc5213ff39.jpg)
![20211217210517_1](https://user-images.githubusercontent.com/96257445/146625802-cf6790be-08f0-4221-8b93-904a9cfe2523.jpg)
![20211217210520_1](https://user-images.githubusercontent.com/96257445/146625803-d8f1fbe5-a31b-4e17-8433-83ff92ad35a9.jpg)
![20211217210523_1](https://user-images.githubusercontent.com/96257445/146625805-6e7c21f9-6992-4ce1-b835-f591e57441b3.jpg)

at SimulationManagerBase`2.SimulationStep (int) <0x0004c>
at TransferManager.ISimulationManager.SimulationStep (int) <0x00024>
at SimulationManager.SimulationStep () <0x00693>
at SimulationManager.SimulationThread () <0x0018a>

System.NullReferenceException: Object reference not set to an instance of an object
at Klyte.TransportLinesManager.Utils.TLMDepotUtils.GetAllDepotsFromCity (Klyte.TransportLinesManager.Extensions.TransportSystemDefinition) <0x001a8>
at Klyte.TransportLinesManager.Extensions.ExtensionStaticExtensionMethods.GetAllowedDepots<Klyte.TransportLinesManager.Interfaces.IBasicExtension> (Klyte.TransportLinesManager.Interfaces.IBasicExtension,Klyte.TransportLinesManager.Extensions.TransportSystemDefinition,uint16) <0x00072>
at Klyte.TransportLinesManager.Overrides.TLMDepotAIOverrides.SetRandomBuilding (Klyte.TransportLinesManager.Extensions.TransportSystemDefinition,uint16,uint16+) <0x0005c>
at Klyte.TransportLinesManager.Overrides.TLMDepotAIOverrides.StartTransfer (DepotAI,uint16,TransferManager/TransferReason,TransferManager/TransferOffer) <0x002ed>
at (wrapper dynamic-method) DepotAI.DepotAI.StartTransfer_Patch1 (DepotAI,uint16,Building+,TransferManager/TransferReason,TransferManager/TransferOffer) <0x0009a>
at TransferManager.StartTransfer (TransferManager/TransferReason,TransferManager/TransferOffer,TransferManager/TransferOffer,int) <0x00643>
at (wrapper dynamic-method) TransferManager.TransferManager.MatchOffers_Patch1 (TransferManager,TransferManager/TransferReason) <0x0077c>
at TransferManager.SimulationStepImpl (int) <0x00070>
at SimulationManagerBase`2.SimulationStep (int) <0x0004c>
at TransferManager.ISimulationManager.SimulationStep (int) <0x00024>
at SimulationManager.SimulationStep () <0x00693>
at SimulationManager.SimulationThread () <0x0018a>

System.NullReferenceException: Object reference not set to an instance of an object
at Klyte.TransportLinesManager.Utils.TLMDepotUtils.GetAllDepotsFromCity (Klyte.TransportLinesManager.Extensions.TransportSystemDefinition) <0x001a8>
at Klyte.TransportLinesManager.Extensions.ExtensionStaticExtensionMethods.GetAllowedDepots<Klyte.TransportLinesManager.Interfaces.IBasicExtension> (Klyte.TransportLinesManager.Interfaces.IBasicExtension,Klyte.TransportLinesManager.Extensions.TransportSystemDefinition,uint16) <0x00072>
at Klyte.TransportLinesManager.Overrides.TLMDepotAIOverrides.SetRandomBuilding (Klyte.TransportLinesManager.Extensions.TransportSystemDefinition,uint16,uint16+) <0x0005c>
at Klyte.TransportLinesManager.Overrides.TLMDepotAIOverrides.StartTransfer (DepotAI,uint16,TransferManager/TransferReason,TransferManager/TransferOffer) <0x002ed>
at (wrapper dynamic-method) DepotAI.DepotAI.StartTransfer_Patch1 (DepotAI,uint16,Building+,TransferManager/TransferReason,TransferManager/TransferOffer) <0x0009a>
at TransferManager.StartTransfer (TransferManager/TransferReason,TransferManager/TransferOffer,TransferManager/TransferOffer,int) <0x00643>
at (wrapper dynamic-method) TransferManager.TransferManager.MatchOffers_Patch1 (TransferManager,TransferManager/TransferReason) <0x0077c>
at TransferManager.SimulationStepImpl (int) <0x00070>
at SimulationManagerBase`2.SimulationStep (int) <0x0004c>
at TransferManager.ISimulationManager.SimulationStep (int) <0x00024>
at SimulationManager.SimulationStep () <0x00693>
at SimulationManager.SimulationThread () <0x0018a>

List of Mods as follows:

Harmony 2.0.4-4 (ID=2040656402)                             activated
Hard Mode (ID=18446744073709551615)                         deactivated
Unlimited Money (ID=18446744073709551615)                   activated
Unlimited Oil And Ore (ID=18446744073709551615)             activated
Unlimited Soil (ID=18446744073709551615)                    activated
Unlock All (ID=18446744073709551615)                        activated
Wallbass FM (ID=1081195940)                                 activated
Procedural Objects 1.7.4 (ID=1094334744)                    activated
Music pack: Michael Jackson Greatest Hits! (ID=1156097512)  activated
Cities Of Tomorrow Music (ID=1200560615)                    activated
SimCity SNES Music Pack (ID=1207763962)                     activated
Extended Game Options (ID=1237383751)                       activated
Network Tiling (ID=1274199764)                              activated
Music pack: Hardstyle Radio (ID=1295761551)                 activated
Transport Lines Manager 14.1 (ID=1312767991)                activated
Addresses & Names Mod 3.1 (ID=1322787091)                   activated
Back to the 80's - Synthwave & Retro (ID=1335338525)        activated
ClassicHits - 70s,80s,90s (ID=1336375564)                   activated
Parkify r1.0.5 (ID=1393452031)                              activated
Advanced Stop Selection (ID=1394468624)                     activated
Additive Shader (ID=1410003347)                             activated
Real Time (ID=1420955187)                                   activated
Snooper (ID=1435741602)                                     activated
Parallel Road Tool 2.0.3 (ID=1440928803)                    activated
Simcity Cities of Tomorrow music pack (ID=1468593438)       activated
UltimateMod v2.9  (ID=1498036881)                           activated
Railway Replacer (ID=1530376523)                            activated
CNSoundPack (ID=1541828679)                                 activated
Industries Vehicle Converter (ID=1546357276)                activated
Advanced Vehicle Options 1.9.5 (ID=1548831935)              activated
Trailer Variation Loader (ID=1552053911)                    activated
Show It! (ID=1556715327)                                    activated
Rebalanced Industries (ID=1562650024)                       activated
Los Santos Rock Radio (ID=1564632871)                       activated
Other Rail Track Speed Increaser 1.1.0 (ID=1586774819)      activated
More Advanced Toolbar (ID=1597852915)                       activated
Move It 2.9.4 (ID=1619685021)                               activated
AST: SBB Sound Pack (ID=1624184698)                         deactivated
Bulldoze It! (ID=1627986403)                                activated
AST: CFF Sound Pack (ID=1628985258)                         activated
AST: ÖBB Sound Pack (ID=1629745074)                         activated
Vehicle Wealthizer 3 (ID=1633580257)                        deactivated
TM:PE 11.5.2 STABLE (ID=1637663252)                         activated
Watch It! (ID=1643902284)                                   activated
Traffic Congestion Report (ID=1651036644)                   activated
Rebuild It! (ID=1656549865)                                 activated
Historical Districts (ID=1658773932)                        activated
Empty It! (ID=1661072176)                                   activated
Custom Animation Loader (CAL) (ID=1664509314)               activated
Employ Overeducated Workers V2 (ID=1674732053)              activated
Smart Intersection Builder (ID=1677913611)                  activated
Remove All Animals (ID=1706704781)                          activated
Optimised Outside Connections (ID=1721492498)               activated
Network Skins (ID=1758376843)                               activated
Broken Node Detector 0.6 (ID=1777173984)                    activated
US Route Shields (ID=1789133988)                            activated
SimCity (2013) + Cities of Tomorrow Music Pack (ID=1791020927) activated
Customize It! Extended (ID=1806759255)                      activated
Klyte's Fine Road Anarchy 2.0.2 (ID=1844440354)             activated
Klyte's Fine Road Tool 2.0.4 (ID=1844442251)                activated
Prop Painter 4.0 + PaintUI (ID=1869561285)                  deactivated
Custom Effect Loader (ID=1886877404)                        activated
Problem Info (v1.0.7402.18207) (ID=1927186256)              activated
Open Street Cities (ID=1957515502)                          deactivated
OxylonEuroSoundpackNED (ID=1969432061)                      activated
TrainPackDBAG (ID=2008325200)                               deactivated
RICO Revisited 2.4.10  (ID=2016920607)                      activated
Lifecycle Rebalance Revisited 1.5.5  (ID=2027161563)        activated
Instant Return To Desktop (ID=2037888659)                   activated
Patch Loader Mod v2.1.2 (ID=2041457644)                     activated
Extended Error Reporting (ID=2055465280)                    activated
Path Snapping (ID=2060132379)                               deactivated
Node Spacer (ID=2085018096)                                 activated
Shared Stop Enabler (ID=2096382380)                         activated
Repaint 1.4.2 (ID=2101551127)                               activated
Transport Vehicle Return Patch (ID=2101977903)              activated
FPS Booster 0.6.2 (ID=2105755179)                           activated
Write The Signs 0.3 (ID=2139980554)                         activated
Intersection Marking Tool 1.8.2.2 (ID=2140418403)           activated
Picker 1.6.5 (ID=2172488844)                                activated
Find It! [BETA] 2.7.3-beta1 (ID=2187834843)                 activated
BOB - the tree and prop replacer 0.8.6.2 (ID=2197863850)    deactivated
TramSoundAddON (ID=2220870813)                              activated
Realistic Population 2 2.0 rc6 (ID=2243670411)              activated
MetroSoundDefinition_SH (ID=2247089222)                     activated
Unified UI 2.1 (ID=2255219025)                              activated
Express Bus Services (ID=2262054175)                        activated
Trolleybus Trailer AI (ID=2275749683)                       activated
Vehicle Master Control 1 (ID=2299901014)                    activated
Smarter Firefighters: Improved AI (ID=2346565561)           activated
Train Display Mod (ID=2380878816)                           activated
Zoning Adjuster 1.4  (ID=2389414419)                        deactivated
Gravity Module (ID=2404099470)                              activated
RON - the network replacer 0.8 (ID=2405917899)              activated
Population Demographics (ID=2409471930)                     activated
Building Theme: American Trailer Homes (ID=2414098508)      deactivated
Adaptive Roads 2.4 (ID=2414618415)                          activated
Load Order Mod 1.2 (ID=2448824112)                          activated
Detailed Employment and Workplaces Info (Industry Areas included :)) (ID=2448923697) deactivated
Node Controller Renewal 3.1.3.1 (ID=2472062376)             activated
CSL Music Mod (ID=2474585115)                               activated
CSL Commuter Destination (ID=2475986859)                    activated
Intercity Bus Control (ID=2499771767)                       activated
SwitchMAD_Desktop (ID=2535099806)                           activated
Network Multitool 1.2.0.3 (ID=2560782729)                   activated
Real Train Sound (ID=2573531978)                            activated
Real Train Sound (ID=2607683510)                            activated
Upgrade Untouchable 1 (ID=2629141193)                       activated
Express Bus Services (TLM plugin) (ID=2630529375)           activated
Effects Module (ID=2632235148)                              deactivated
Compatibility Report v0.6.2 beta (ID=2633433869)            activated
A Compact MAD Commander - DEUSX (ID=2634380809)             deactivated
More CitizenUnits 0.4 (ID=2654364627)                       activated
Super Demand (ID=406102887)                                 activated
City Vitals Watch (ID=410151616)                            activated
Precision Engineering (ID=445589127)                        activated
Mesh Info 1.3.3 (ID=453956891)                              activated
Unlimited Trees Mod (ID=455403039)                          deactivated
Building Themes (ID=466158459)                              activated
Not So Unique Buildings (ID=466834228)                      activated
UnlimitedOutsideConnections (ID=497033453)                  activated
Extra Landscaping Tools (ID=502750307)                      activated
Building Theme: Brooklyn (ID=505120347)                     activated
More Network Stuff (ID=512314255)                           activated
Extra Train Station Tracks (ID=515489008)                   activated
Prefab Hook (ID=530771650)                                  activated
Phantom Lane Remover (ID=536250255)                         deactivated
Sub-Buildings Enabler (ID=553501635)                        activated
Random Tree Rotation (ID=556784825)                         deactivated
Building Theme: Manhattan (ID=561699875)                    activated
81 Tiles (Fixed for C:S 1.2+) (ID=576327847)                activated
Prop & Tree Anarchy (ID=593588108)                          activated
Sub-Buildings Tabs (ID=608517757)                           activated
Environment Changer (ID=611254368)                          deactivated
Workshop RICO Settings (ID=629850626)                       activated
Sim City 4 Music Pack (ID=633993845)                        activated
Sim City 3000 Music Pack (ID=634046315)                     activated
Sim City 2000 Music Pack (ID=634143359)                     activated
Sim City (2013) Music Pack (ID=634216395)                   activated
Elevated Stops Enabler (ID=634913093)                       activated
Quay Anarchy (ID=650436109)                                 activated
First Person Camera (ID=650805785)                          activated
CSLInvisibleVehicleRemover (ID=662587975)                   deactivated
Loading Screen Mod (ID=667342976)                           deactivated
Tram Station Track (ID=707497031)                           activated
Anno 2070 Music Pack (ID=718886717)                         activated
One-Way Train Tracks (ID=724382534)                         activated
Infinite Goods (ID=725555912)                               activated
Decal Prop Fix (ID=767233815)                               activated
Catenary Replacer (ID=774449380)                            activated
Vehicle Effects 1.9.1 (ID=780720853)                        activated
Prop Snapping (ID=787611845)                                activated
Prop Precision 1.0.1 (ID=791221322)                         activated
Train Converter (ID=795514116)                              activated
Less Steam (ID=812107110)                                   activated
Network Extensions 2 (ID=812125426)                         activated
Improved Content Manager (ID=814498849)                     activated
Extra Vehicle Effects (ID=815103125)                        activated
Metro Overhaul (ID=816260433)                               activated
Ambient Sounds Tuner (ID=818641631)                         activated
Spawn Points Fix (ID=820157360)                             activated
Loading Screen Mod [Test] (ID=833779378)                    activated
CSL Map View (ID=845665815)                                 activated
Any Road Outside Connections (ID=883332136)                 activated
Music pack: Cities SynthPop (ID=887074370)                  activated
Theme Decals (ID=895061550)                                 deactivated
Camera Positions Utility (ID=898480258)                     activated
No Problem Notifications (ID=917543381)                     activated
Transparency LOD Fix + Cloud Assets Enabler (ID=922939393)  activated
Plop Growables (ID=924884948)                               activated
SingleTrainTrackAI (ID=949504539)                           activated
PropRotating Params (ID=954067599)                          activated
Music pack: GTAV Soundtrack (ID=971298487)                  activated
Sort Mod Settings (ID=973512634)                            activated

**Comment by Boliqua2** [comment] 2021-12-18 03:34
Attached output.log as well

[output_log - Copy (2).txt](https://github.com/klyte45/TransportLinesManager/files/7738650/output_log.-.Copy.2.txt)

**Comment by 37Am** [comment] 2021-12-26 20:42
I have the same problem. I have tried a few things. Deleting the depot and the Metro lines seemed to work at first and I could even add a new depot and a few short new lines for testing purposes. On these new lines everything worked normal, but as I started to rebuild my regular lines, the error came back. As far as I could see, this always happened, when the metro trains needed to go directly from the depot to some of the more far away stations.

I hope this helps to get this great mod working with metro-overhaul again.

**Comment by Transportation-master-kcl** [comment] 2021-12-27 02:20
Do these mean that TLM is incompatible with Metro Overhaul?

**Comment by 37Am** [comment] 2021-12-27 23:31
@Transportation-master-kcl not necessarily, this is just a problem since the last updates and is hopefully resolvable. Additionally, the problem isn't always triggered. As I described, it is only a problem, if the trains have to travel far to get from the depot to the stations (as far as I tested, this happens, when they have to go more than one or two tiles). So, as far as I have tested, it is entirely possible to operate shorter lines, as long as only nearby depots are assigned.

**Comment by Oninaig** [comment] 2021-12-29 23:26
Just as an update, I am getting this same error on a simple inner-city metro line and I **dont** have Metro Overhaul. Attached is my output log showing the same nullreference at Klyte.TransportLinesManager.Utils.TLMDepotUtils.GetAllDepotsFromCity
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7790937/output_log.txt)

**Comment by klyte45** [comment] 2022-01-03 17:15
Okay, I guess I found the problem and a fix may be coming later this week.

**Comment by klyte45** [comment] 2022-01-04 17:57
I forgot to mention. but this was solved in latest patch r9

Closing here

**Closed by klyte45** 2022-01-04 17:57 UTC
Labels: bug

**Comment by Boliqua2** [comment] 2022-01-05 05:43
Thank you for your  help. I very greatly appreciate  it. Enjoy the new year
