### ISSUE TITLE
Custom Settings For Line Not Saving

### ISSUE THREAD

**Issue by studio752** [klyte45/TransportLinesManager#52] opened 2021-03-30 23:37 UTC
It seems like the same issue as #50 but I did not have it until recently, I think after the release to fix that issue.
I have 14 bus lines with custom configs that load and work fine. However the two that I've created recently always revert to a default configuration on load (numbers in white, some large amount of default buses assigned to the route.)

The only TLM related things in my log:
```
Loading /home/user/.local/share/Steam/steamapps/workshop/content/255710/1312767991/TransportLinesManager.dll  [Mods - Internal]
Assembly TransportLinesManager, Version=13.5.0.10000, Culture=neutral, PublicKeyToken=null loaded.  [Mods - Internal]
TLMv13.5 Patching all: com.klyte.redirectors.TLM
TLMv13.5 FallBackDefaultFile
```

**Comment by klyte45** [comment] 2021-03-31 00:11
Can you try it again with debug mode enabled? Then look for if have additional logs near this fallback default file log.

**Comment by BrewBuilding** [comment] 2021-04-10 17:50
I'm having the same problem as studio752. Each time I reload my maps, I have to reset the lines because they've all reverted to defaults. The attached zip file has the logs I found "near" the `
output_log.txt` file.
[CS-TLS-output_log.txt.zip](https://github.com/klyte45/TransportLinesManager/files/6290455/CS-TLS-output_log.txt.zip)

**Comment by klyte45** [comment] 2021-04-10 18:14
Wait, have you loaded a city more than once in same game session? If yes, it really can cause problems, since we modders know that game doesn't deals well with some patch/unpatch operations (this is the reason behind some unification mods, like Harmony 2). So I strongly discourage to load cities in the game more than once in the same game session.

**Comment by BrewBuilding** [comment] 2021-04-10 18:35
No, I can't do anything more than once. If I end a game, I have to quit to desktop, then start up from "ground zero" again, or the map or editor crashes when it's almost finished loading.  It was like that even before I installed any mods.

**Comment by klyte45** [comment] 2021-04-10 18:45
Well, there's a lot of errors like this in your log:
``` 
Invalid list detected!
   at System.Environment.get_StackTrace()
   at PathManager.FindPathPosition(Vector3 position, Service service, Service service2, Service service3, SubService subService3, Level level3, LaneType laneType, VehicleType vehicleType, VehicleType stopType, Boolean allowUnderground, Boolean requireConnect, Single maxDistance, Position ByRef pathPosA, Position ByRef pathPosB, Single ByRef distanceSqrA, Single ByRef distanceSqrB)
   at PathManager.FindPathPosition(Vector3 position, Service service, Service service2, LaneType laneType, VehicleType vehicleType, VehicleType stopType, Boolean allowUnderground, Boolean requireConnect, Single maxDistance, Position ByRef pathPosA, Position ByRef pathPosB, Single ByRef distanceSqrA, Single ByRef distanceSqrB)
   at PathManager.FindPathPosition(Vector3 position, Service service, LaneType laneType, VehicleType vehicleType, Boolean allowUnderground, Boolean requireConnect, Single maxDistance, Position ByRef pathPosA, Position ByRef pathPosB, Single ByRef distanceSqrA, Single ByRef distanceSqrB)
   at PedestrianPathAI.UpdateLaneConnection(UInt16 nodeID, NetNode ByRef data)
   at NetNode.NetNode.UpdateLaneConnection_Patch1(NetNode ByRef , UInt16 )
   at NetManager.SimulationStepImpl(Int32 subStep)
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at NetManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]
```

Might be caused by Roads United because it replace some roads in game, and it can eventually break the transport lines, specially road ones. So, I suspect this is the origin of your problem. Test disabling the Roads United related mods then loading the city.

**Comment by BrewBuilding** [comment] 2021-04-12 03:25
I've done a lot of experimenting, including disabling the three Roads United mods, disabling other mods, cleaning up missing assets, etc.  I never have gotten that city sorted out.  It finally occurred to me to try it with a brand new city.  So I loaded up one of the "factory" maps and ran until I got buses.  In the new city, TLM is saving routes just fine, but Roads United and a couple of other mods are still disabled.  Something is borked with the city where I originally had the problem, or with one of the disabled mods or an asset or something.  If I figure out what's happening, I'll let you know.  But it's obviously a conflict of some sort, or some other brokenness in that city.

**Comment by klyte45** [comment] 2021-04-14 20:43
Well, I guess I found something: I noted while I was playing that some settings in the mod options transport types tab get resetted after reloading a city. This is related with the problem you are having there?

**Comment by BrewBuilding** [comment] 2021-04-15 01:56
That sounds like its related, if not the same problem.  Basically, each time I started up and loaded a savegame, it would have forgotten all of the route settings and I'd have to go back into the menus and set the number of trains/trams/buses/whatever and the "Use separate configuration" (I forget the exact wording) option, and which was the "home station" on each line.  But my experiments show that it's a special case of some sort, possibly involving other mods.  When I started a new game, all was well, and I'm still playing that game a couple of days later, and it's still all ok.

**Comment by klyte45** [comment] 2021-04-16 20:47
Ah! Got it
It's when you choose to don't use prefix common settings for an specific line, so?

**Comment by BrewBuilding** [comment] 2021-04-18 16:27
Well, I never have set prefixes for the lines, if that's what you mean.  I just select _Use Separate Configuration for this line_ and set up the details for that line, without setting up line prefixes.

**Comment by klyte45** [comment] 2021-04-18 16:36
This is what I want to mean. Nice tip.

Anyway, the TLM stuff related to storage for the configurations is being reviewed right now. Once it will be a huge update, I guess it won't be ready so soon, there's the risk to the new data storage system to be incompatible with current system and **maybe it will be released as a new mod due of that**. Note the base of the current storage system of the mod is from 2015 and is being fully replaced now after two minor reforms some years ago

The fix possibly will be available only on this big new version once this problem seems related with how the storage system is working in 13.5. The compatibility mode between systems is a open question for now.

**Comment by BrewBuilding** [comment] 2021-04-18 17:06
Just wanted to say thanks for your fine work, too!

**Comment by klyte45** [comment] 2021-04-19 03:40
Good news: TLM14 must be ready until next weekend. The changes were less difficult than I thought.
The beta branch will be available until tomorrow.

**Closed** 2021-04-29 03:38 UTC
Labels: bug
